# Generated by Django 3.0.8 on 2021-06-02 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
