export const GET_REQUESTS = "GET_REQUESTS";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const EDIT_REQUEST = "EDIT_REQUEST";
export const ADD_REQUEST = "ADD_REQUEST";

export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGES = "CREATE_MESSAGES";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";

export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const DELETE_REPOSITORY = "DELETE_REPOSITORY";
export const EDIT_REPOSITORY = "EDIT_REPOSITORY";
export const ADD_REPOSITORY = "ADD_REPOSITORY";

export const GET_AGREEMENTS = "GET_AGREEMENTS";
export const DELETE_AGREEMENT = "DELETE_AGREEMENT";
export const EDIT_AGREEMENT = "EDIT_AGREEMENT";
export const ADD_AGREEMENT = "ADD_AGREEMENT";