# Generated by Django 2.2.7 on 2019-11-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('university_structure', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StartYears',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('start_year_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.StartYears')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=None)),
                ('retake_count', models.SmallIntegerField(default=0)),
                ('control_type_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.ControlTypes')),
                ('group_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Groups')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Marks')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Students')),
                ('subject_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Teachers')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Terms')),
            ],
        ),
    ]
