# Generated by Django 3.0.8 on 2020-07-06 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='controltypes',
            table='control_types',
        ),
        migrations.AlterModelTable(
            name='marks',
            table='marks',
        ),
        migrations.AlterModelTable(
            name='records',
            table='records',
        ),
        migrations.AlterModelTable(
            name='startyears',
            table='start_years',
        ),
        migrations.AlterModelTable(
            name='terms',
            table='terms',
        ),
    ]
