# Generated by Django 3.0.8 on 2020-07-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0002_auto_20200706_1756'),
        ('people', '0002_auto_20200706_1800'),
        ('university_structure', '0002_auto_20200706_1800'),
        ('information', '0002_auto_20200706_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retakes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=None)),
                ('retake_count', models.SmallIntegerField(default=0)),
                ('control_type_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.ControlTypes')),
                ('group_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Groups')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Marks')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Students')),
                ('subject_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Teachers')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Terms')),
            ],
            options={
                'db_table': 'retakes',
            },
        ),
    ]
