# Generated by Django 3.0.8 on 2020-07-12 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('information', '0006_auto_20200712_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retakes',
        ),
    ]
