# Generated by Django 3.0.8 on 2021-06-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(default=None, max_length=60, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('degree', models.CharField(default=None, max_length=150, null=True)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='university_structure.Departments')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(default=None, max_length=60, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('average_rating', models.FloatField(default=None)),
                ('update_date', models.DateTimeField(default=None)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='university_structure.Groups')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
