# Generated by Django 2.2.7 on 2019-11-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(default=None, max_length=60, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('degree', models.CharField(default=None, max_length=150, null=True)),
                ('token', models.CharField(default=None, max_length=120, null=True)),
                ('user_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(default=None, max_length=60, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('average_rating', models.FloatField(default=None)),
                ('update_date', models.DateTimeField(default=None)),
                ('group_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Groups')),
            ],
        ),
    ]
