# Generated by Django 3.0.8 on 2020-07-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('university_structure', '0004_auto_20200712_1846'),
        ('people', '0004_auto_20200712_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.Groups'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.Groups'),
        ),
    ]
