# Generated by Django 3.0.8 on 2020-07-12 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0005_auto_20200712_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='user_id',
        ),
    ]
