# Generated by Django 3.0.8 on 2020-07-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('information', '0001_initial'),
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBlocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'subject_blocks',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('department_id',
                 models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='university_structure.Departments')),
                ('education_program_id',
                 models.ForeignKey(db_column='education_program_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='university_structure.EducationPrograms')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectsSubjectBlocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_block_id',
                 models.ForeignKey(db_column='subject_block_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='subjects.SubjectBlocks')),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE,
                                                 to='subjects.Subjects')),
            ],
            options={
                'db_table': 'subjects_subject_blocks',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=None)),
                ('retake_count', models.SmallIntegerField(default=0)),
                ('control_type_id',
                 models.ForeignKey(db_column='control_type_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='information.ControlTypes')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE,
                                               to='university_structure.Groups')),
                ('mark_id', models.ForeignKey(db_column='mark_id', on_delete=django.db.models.deletion.CASCADE,
                                              to='information.Marks')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE,
                                                 to='people.Students')),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE,
                                                 to='subjects.Subjects')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE,
                                                 to='people.Teachers')),
                ('term_id', models.ForeignKey(db_column='term_id', on_delete=django.db.models.deletion.CASCADE,
                                              to='information.Terms')),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
