# Generated by Django 3.0.8 on 2020-07-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
