# Generated by Django 3.0.8 on 2021-06-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_records_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='subject_block_id',
            field=models.ForeignKey(db_column='subject_block_id', default=5, on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectBlocks'),
            preserve_default=False,
        ),
    ]
