# Generated by Django 2.2.7 on 2019-11-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBlocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('educational_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                             to='university_structure.EducationalPrograms')),
                ('faculty_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Faculties')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsSubjectBlocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_block_id', models.ManyToManyField(to='departments.SubjectBlocks')),
                ('subject_id', models.ManyToManyField(to='departments.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('faculty_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Faculties')),
            ],
        ),
    ]
