# Generated by Django 3.0.8 on 2020-07-06 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='subjectblocks',
            table='subject_blocks',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='subjectssubjectblocks',
            table='subjects_subject_blocks',
        ),
    ]
