# Generated by Django 3.0.8 on 2020-07-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('university_structure', '0005_auto_20200712_1853'),
        ('departments', '0004_auto_20200712_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='faculty_id',
            field=models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.Faculties'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='educational_program_id',
            field=models.ForeignKey(db_column='educational_program_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.EducationalPrograms'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='faculty_id',
            field=models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.Faculties'),
        ),
        migrations.AlterField(
            model_name='subjectssubjectblocks',
            name='subject_block_id',
            field=models.ManyToManyField(db_column='subject_block_id', to='departments.SubjectBlocks'),
        ),
        migrations.AlterField(
            model_name='subjectssubjectblocks',
            name='subject_id',
            field=models.ManyToManyField(db_column='subject_id', to='departments.Subjects'),
        ),
    ]
