# Generated by Django 3.0.8 on 2020-07-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0005_auto_20200712_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_block_id',
            field=models.ForeignKey(db_column='subject_block_id', default=3,
                                    on_delete=django.db.models.deletion.CASCADE, to='departments.SubjectBlocks'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubjectsSubjectBlocks',
        ),
    ]
