# Generated by Django 2.2.7 on 2019-11-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('educational_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                             to='university_structure.EducationalPrograms')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                        to='university_structure.Specializations')),
            ],
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.Faculties'),
        ),
    ]
