# Generated by Django 3.0.8 on 2020-07-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'education_levels',
            },
        ),
        migrations.CreateModel(
            name='EducationPrograms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('main_department_id',
                 models.ForeignKey(db_column='main_department_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='university_structure.Departments')),
            ],
            options={
                'db_table': 'educational_programs',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('faculty_id', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE,
                                                 to='university_structure.Faculties')),
            ],
            options={
                'db_table': 'specializations',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('education_program_id',
                 models.ForeignKey(db_column='education_program_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='university_structure.EducationPrograms')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AddField(
            model_name='educationprograms',
            name='specialization_id',
            field=models.ForeignKey(db_column='specialization_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.Specializations'),
        ),
        migrations.AddField(
            model_name='educationprograms',
            name='start_year_id',
            field=models.ForeignKey(db_column='start_year_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='information.StartYears'),
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty_id',
            field=models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.Faculties'),
        ),
    ]
