# Generated by Django 3.0.8 on 2020-07-16 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='educationprograms',
            table='education_programs',
        ),
    ]
