# Generated by Django 3.0.8 on 2020-07-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('university_structure', '0002_auto_20200716_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationLevel',
            new_name='EducationLevels',
        ),
        migrations.AddField(
            model_name='educationprograms',
            name='education_level_id',
            field=models.ForeignKey(db_column='education_level_id', default=12,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='university_structure.EducationLevels'),
            preserve_default=False,
        ),
    ]
