# Generated by Django 3.0.8 on 2020-07-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('university_structure', '0003_auto_20200716_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializations',
            name='code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
